# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
excerpt_separator:   '###-###'
# Setup
title:               'CS 6501: Text Mining'
tagline:             'Spring 2015 &middot; <a href="http://www.cs.virginia.edu/">CS@UVa</a>'
description:         'Formula for this course: <br><b>Text Mining = Data Mining + Text Data</b>'
host:								 'http://www.cs.virginia.edu/'
baseurl:             /~hw5x/Course/Text-Mining-2015-Spring/_site

# About/contact
author:
  name:              Hongning Wang
  url:               'http://www.cs.virginia.edu/~hw5x/'
  email:             hw5x@virginia.edu

# Custom vars
version:             1.0.0
